name: RingCentral Data Update V1

permissions:
  contents: write

on:
  schedule:
    - cron: '*/45 * * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas numpy

      - name: Run script
        run: python script.py
        env:
          RC_CLIENT_ID: ${{ secrets.RC_CLIENT_ID }}
          RC_CLIENT_SECRET: ${{ secrets.RC_CLIENT_SECRET }}
          RC_JWT: ${{ secrets.RC_JWT }}

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ringcentral_call_logs.csv
          git commit -m "Auto update data" || echo "No changes"
          git push
